
on:
  push:
    tags: ["v*"]
permissions:
  contents: write
jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
            version: '~> v2'
            args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
